version: '3.8'

services:
  sql_injection:
    build:
      context: .
      dockerfile: sql-injection.Dockerfile
      args:
        - HOST_UID=${HOST_UID}
    container_name: sql-injection
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./logs:/var/log/sql-injection
    restart: unless-stopped
