version: '3.8'

services:
  sql_injection:
    build:
      context: ./src
      dockerfile: sql_injection.Dockerfile
      args:
        - UID=${UID}
    container_name: sql-injection
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./logs:/var/log/app
    restart: unless-stopped
