version: '3.8'

services:
  cowrie:
    image: cowrie/cowrie:latest
    container_name: cowrie
    ports:
      - "22:2222"
    volumes:
      - ./config/userdb.txt:/cowrie/cowrie-git/etc/userdb.txt
      - cowrie-log:/cowrie/cowrie-git/var/log/cowrie
    restart: always

volumes:
  cowrie-log:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/log/cowrie'